"use client";
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Album={ok:boolean;message?:string;event_id?:string;allow_guest_messages?:boolean;allow_guest_photos?:boolean;event_name?:string;memories?:{author_name:string;message:string;submitted_at:string}[];photos?:{original_filename:string;storage_path:string;uploaded_at:string}[]};
export default function PublicAlbum({token}:{token:string}){
 const sb=createClient();const [album,setAlbum]=useState<Album|null>(null);const [author,setAuthor]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [photo,setPhoto]=useState<File|null>(null);
 async function load(){const {data,error}=await sb.rpc("get_public_event_album",{p_token:token});if(error)throw error;setAlbum(data as Album)}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"Não foi possível abrir o álbum."))},[token]);
 async function uploadPhoto(){if(!photo||!album?.event_id)return;setBusy(true);setError("");setNotice("");try{const ext=photo.type==="image/jpeg"?(photo.name.toLowerCase().endsWith(".jpeg")?"jpeg":"jpg"):photo.type==="image/png"?"png":photo.type==="image/webp"?"webp":"";if(!ext)throw new Error("Use uma imagem JPEG, PNG ou WebP.");if(photo.size>10*1024*1024)throw new Error("A imagem deve ter até 10 MB.");const filename=crypto.randomUUID()+"."+ext;const path=album.event_id+"/"+token+"/"+filename;const {error:uploadError}=await sb.storage.from("event-memory-photos").upload(path,photo,{contentType:photo.type,upsert:false});if(uploadError)throw uploadError;const {data,error}=await sb.rpc("register_public_event_photo",{p_token:token,p_storage_path:path,p_filename:photo.name,p_mime_type:photo.type,p_size_bytes:photo.size});if(error){await sb.storage.from("event-memory-photos").remove([path]);throw error}setNotice((data as {message?:string})?.message||"Foto enviada.");setPhoto(null);await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível enviar a foto.")}finally{setBusy(false)}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");setNotice("");try{const {data,error}=await sb.rpc("submit_public_event_memory",{p_token:token,p_author_name:author,p_message:message});if(error)throw error;setNotice((data as {message?:string})?.message||"Mensagem enviada.");setAuthor("");setMessage("");await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível enviar a mensagem.")}finally{setBusy(false)}}
 return <main className="public-album"><div className="public-album-card"><span className="eyebrow">CELEBRA PREMIUM · ÁLBUM DE MEMÓRIAS</span>{!album&&!error?<p>Carregando álbum…</p>:album?.ok?<><h1>{album.event_name||"Memórias do evento"}</h1><p className="public-album-intro">Compartilhe uma mensagem especial e relembre os melhores momentos.</p>{error&&<div className="form-error">{error}</div>}{notice&&<div className="checkin-result accepted">{notice}</div>}{album.allow_guest_photos&&<section className="public-memory-form"><h2>Compartilhe uma foto</h2><label>Escolha uma imagem<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label><small>JPEG, PNG ou WebP, até 10 MB. A foto pode passar por moderação antes de ser publicada.</small><button className="primary-button" type="button" disabled={busy||!photo} onClick={()=>void uploadPhoto()}>{busy?"Enviando…":"Enviar foto"}</button></section>}{album.allow_guest_messages&&<form className="public-memory-form" onSubmit={submit}><label>Seu nome<input value={author} onChange={e=>setAuthor(e.target.value)} minLength={2} maxLength={120} required placeholder="Como podemos identificar você?"/></label><label>Sua mensagem<textarea value={message} onChange={e=>setMessage(e.target.value)} minLength={1} maxLength={3000} required rows={4} placeholder="Escreva uma mensagem para este momento…"/></label><button className="primary-button" disabled={busy}>{busy?"Enviando…":"Enviar mensagem"}</button><small>Para manter o álbum respeitoso, a mensagem pode passar por moderação antes de aparecer.</small></form>}<section className="public-memories"><h2>Mensagens publicadas</h2>{(album.memories||[]).map((m,i)=><article key={i}><strong>{m.author_name}</strong><p>{m.message}</p><small>{new Date(m.submitted_at).toLocaleDateString("pt-BR")}</small></article>)}{!album.memories?.length&&<p className="muted">As mensagens aprovadas aparecerão aqui.</p>}</section><p className="public-album-footer">Compartilhamento privado por link · Celebra Premium</p></>:<><h1>Álbum indisponível</h1><p>{error||album?.message||"Este link expirou ou foi revogado."}</p></>}</div></main>
}