"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import {useEffect,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Checkin={checkin_id:string;guest_id:string;guest_name:string;family_name:string;status:string;checked_in_at:string;checked_in_by:string|null;reversal_reason:string|null};
type Result={result:string;message:string;guest_name?:string;family_name?:string;checked_in_at?:string;checkin_id?:string};
export default function ReceptionConsole({eventId}:{eventId:string}){
 const sb=createClient();const [token,setToken]=useState(""),[busy,setBusy]=useState(false),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(""),[rows,setRows]=useState<Checkin[]>([]),[camera,setCamera]=useState(false),[reverseId,setReverseId]=useState(""),[reason,setReason]=useState("");
 const videoRef=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);const scanRef=useRef(false);
 async function load(){const {data,error}=await sb.rpc("list_event_checkins",{p_event_id:eventId,p_limit:100});if(error)throw error;setRows(data||[])}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"Não foi possível carregar o histórico."));return()=>{streamRef.current?.getTracks().forEach(t=>t.stop())}},[eventId]);
 async function validate(raw=token){setBusy(true);setError("");setResult(null);try{let candidate=raw.trim();const m=candidate.match(/\/convite\/([^/?#]+)/);if(m)candidate=decodeURIComponent(m[1]);const {data,error}=await sb.rpc("process_event_checkin",{p_event_id:eventId,p_token:candidate});if(error)throw error;setResult(data as Result);setToken("");await load()}catch(e){setError(e instanceof Error?e.message:"Falha ao validar ingresso.")}finally{setBusy(false)}}
 async function startCamera(){setError("");try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});streamRef.current=stream;setCamera(true);if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}const Detector=(window as any).BarcodeDetector;if(!Detector)throw new Error("Este navegador não oferece leitura QR nativa. Cole o link ou token do convite no campo.");const detector=new Detector({formats:["qr_code"]});scanRef.current=true;const loop=async()=>{if(!scanRef.current||!videoRef.current)return;try{const found=await detector.detect(videoRef.current);if(found?.length){scanRef.current=false;const value=found[0].rawValue||"";streamRef.current?.getTracks().forEach(t=>t.stop());setCamera(false);await validate(value);return}}catch{}requestAnimationFrame(()=>void loop())};requestAnimationFrame(()=>void loop())}catch(e){streamRef.current?.getTracks().forEach(t=>t.stop());setCamera(false);setError(e instanceof Error?e.message:"Não foi possível iniciar a câmera.")}}
 function stopCamera(){scanRef.current=false;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setCamera(false)}
 async function reverse(){if(!reverseId)return;setBusy(true);setError("");try{const {error}=await sb.rpc("reverse_event_checkin",{p_checkin_id:reverseId,p_reason:reason});if(error)throw error;setResult({result:"reversed",message:"Entrada revertida e registrada na auditoria."});setReverseId("");setReason("");await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível reverter a entrada.")}finally{setBusy(false)}}
 const accepted=rows.filter(r=>r.status==="checked_in").length;
 return <div className="reception-layout"><section className="panel reception-scan"><div className="panel-heading"><div><h2>Validar ingresso</h2><p>Leia o QR Code ou cole o link/token individual.</p></div><span className="reception-count">{accepted} entradas válidas</span></div><form className="token-form" onSubmit={e=>{e.preventDefault();void validate()}}><label>Link ou token do convite<input value={token} onChange={e=>setToken(e.target.value)} placeholder="Cole aqui o link ou token do QR Code" autoComplete="off"/></label><button className="primary-button" disabled={busy||!token.trim()}>Validar entrada</button><button type="button" className="secondary-button" disabled={busy||camera} onClick={()=>void startCamera()}>Abrir câmera</button></form><div className="camera-box" style={{display:camera?"block":"none"}}><video ref={videoRef} playsInline muted/><p>Posicione o QR Code dentro da imagem.</p><button className="secondary-button" onClick={stopCamera}>Parar câmera</button></div>{result&&<div className={"checkin-result "+result.result}><strong>{result.message}</strong>{result.guest_name&&<span>{result.guest_name}{result.family_name?" · "+result.family_name:""}</span>}{result.checked_in_at&&<span>Registrado em {new Date(result.checked_in_at).toLocaleString("pt-BR")}</span>}</div>}{error&&<div className="form-error">{error}</div>}<p className="muted small">O banco valida evento, validade, revogação, confirmação final e duplicidade simultânea.</p></section><section className="panel"><div className="panel-heading"><div><h2>Histórico de entradas</h2><p>Últimos registros de check-in do evento.</p></div><button className="secondary-button" onClick={()=>void load()} disabled={busy}>Atualizar</button></div><div className="checkin-list">{rows.map(r=><div className="checkin-row" key={r.checkin_id}><div><strong>{r.guest_name}</strong><span>{r.family_name} · {new Date(r.checked_in_at).toLocaleString("pt-BR")}</span><small>{r.status==="checked_in"?"Entrada válida":"Entrada revertida"}{r.reversal_reason?" · Motivo: "+r.reversal_reason:""}</small></div><div>{r.status==="checked_in"&&<button className="text-button-static danger-text" onClick={()=>{setReverseId(r.checkin_id);setReason("")}}>Reverter</button>}</div></div>)}{!rows.length&&<div className="empty">Nenhuma entrada registrada.</div>}</div></section>{reverseId&&<div className="modal-backdrop"><section className="panel reversal-modal"><h2>Reverter check-in</h2><p>Informe um motivo auditável. A reversão exige permissão de gestão do evento.</p><label>Motivo<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5} placeholder="Ex.: ingresso validado por engano"/></label><div className="invite-actions"><button className="secondary-button" onClick={()=>setReverseId("")}>Cancelar</button><button className="danger-button" disabled={busy||reason.trim().length<5} onClick={()=>void reverse()}>Confirmar reversão</button></div></section></div>}</div>
}
