"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Memory={id:string;author_name:string;message:string;status:string;submitted_at:string;moderation_note:string|null};
type Photo={id:string;storage_path:string;original_filename:string;status:string;uploaded_at:string;moderation_note:string|null};
type Data={memories:Memory[];photos:Photo[];settings:{public_enabled:boolean;allow_guest_messages:boolean;allow_guest_photos:boolean;require_moderation:boolean}|null};
export default function MemoryManager({eventId}:{eventId:string}){
 const sb=createClient();const [data,setData]=useState<Data>({memories:[],photos:[],settings:null});const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [allowMessages,setAllowMessages]=useState(true);const [allowPhotos,setAllowPhotos]=useState(true);const [moderation,setModeration]=useState(true);const [publicEnabled,setPublicEnabled]=useState(false);const [shareUrl,setShareUrl]=useState("");
 async function load(){const {data,error}=await sb.rpc("list_event_memories",{p_event_id:eventId});if(error)throw error;const d=(data||{memories:[],photos:[],settings:null}) as Data;setData(d);if(d.settings){setAllowMessages(d.settings.allow_guest_messages);setAllowPhotos(d.settings.allow_guest_photos);setModeration(d.settings.require_moderation);setPublicEnabled(d.settings.public_enabled)}}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"Falha ao carregar álbum."))},[eventId]);
 async function moderate(id:string,action:"approve"|"reject"|"hide",photo=false){setBusy(true);setError("");setNotice("");try{const {error}=await sb.rpc(photo?"moderate_event_memory_photo":"moderate_event_memory",{[photo?"p_photo_id":"p_memory_id"]:id,p_action:action,p_note:"Moderado pela equipe do evento"});if(error)throw error;setNotice(action==="approve"?"Conteúdo aprovado.":action==="reject"?"Conteúdo rejeitado.":"Conteúdo ocultado.");await load()}catch(e){setError(e instanceof Error?e.message:"Falha na moderação.")}finally{setBusy(false)}}
 async function createShareLink(){setBusy(true);setError("");setNotice("");try{const {data,error}=await sb.rpc("rotate_event_album_token",{p_event_id:eventId});if(error)throw error;const token=(data as {token?:string})?.token;if(!token)throw new Error("Não foi possível criar o link.");const url=window.location.origin+"/album/"+token;setShareUrl(url);setNotice("Link protegido criado. Copie e guarde agora; o token não será exibido novamente.");}catch(e){setError(e instanceof Error?e.message:"Falha ao criar link.")}finally{setBusy(false)}}
 async function revokeShareLink(){setBusy(true);setError("");setNotice("");try{const {error}=await sb.rpc("revoke_event_album_token",{p_event_id:eventId});if(error)throw error;setShareUrl("");setNotice("Link público revogado.");}catch(e){setError(e instanceof Error?e.message:"Falha ao revogar link.")}finally{setBusy(false)}}
 async function saveSettings(){setBusy(true);setError("");setNotice("");try{const {error}=await sb.rpc("update_event_album_settings",{p_event_id:eventId,p_public_enabled:publicEnabled,p_allow_messages:allowMessages,p_allow_photos:allowPhotos,p_require_moderation:moderation});if(error)throw error;setNotice("Configurações do álbum salvas.");await load()}catch(e){setError(e instanceof Error?e.message:"Falha ao salvar configurações.")}finally{setBusy(false)}}
 const pendingMessages=data.memories.filter(m=>m.status==="pending"),pendingPhotos=data.photos.filter(p=>p.status==="pending");
 return <div className="memory-manager">{error&&<div className="form-error">{error}</div>}{notice&&<div className="checkin-result accepted">{notice}</div>}
 <div className="gift-totals"><article><span>Mensagens</span><strong>{data.memories.length}</strong></article><article><span>Fotos cadastradas</span><strong>{data.photos.length}</strong></article><article><span>Aguardando moderação</span><strong>{pendingMessages.length+pendingPhotos.length}</strong></article></div>
 <section className="panel"><div className="panel-heading"><div><h2>Configurações do álbum</h2><p>O conteúdo enviado por convidados fica pendente até ser aprovado, por padrão.</p></div></div><div className="memory-settings"><label><input type="checkbox" checked={publicEnabled} onChange={e=>setPublicEnabled(e.target.checked)}/> Álbum público habilitado</label><label><input type="checkbox" checked={allowMessages} onChange={e=>setAllowMessages(e.target.checked)}/> Permitir mensagens</label><label><input type="checkbox" checked={allowPhotos} onChange={e=>setAllowPhotos(e.target.checked)}/> Permitir fotos</label><label><input type="checkbox" checked={moderation} onChange={e=>setModeration(e.target.checked)}/> Exigir moderação antes de publicar</label><button className="primary-button" disabled={busy} onClick={()=>void saveSettings()}>Salvar configurações</button></div><div className="memory-share"><h3>Compartilhamento protegido</h3><p>Gere um link aleatório para convidados. Gere outro para invalidar o anterior; o link completo só aparece no momento da criação.</p><div className="memory-actions"><button className="secondary-button" disabled={busy||!publicEnabled} onClick={()=>void createShareLink()}>Gerar link protegido</button><button className="secondary-button" disabled={busy} onClick={()=>void revokeShareLink()}>Revogar link</button></div>{shareUrl&&<div className="share-url"><input aria-label="Link do álbum" readOnly value={shareUrl}/><button className="primary-button" onClick={()=>void navigator.clipboard.writeText(shareUrl)}>Copiar link</button></div>}</div><p className="muted small">O envio público de fotos ainda não está habilitado; o link permite visualizar mensagens aprovadas e enviar mensagens conforme as configurações.</p></section>
 <section className="panel"><div className="panel-heading"><div><h2>Mensagens de convidados</h2><p>Revise mensagens antes de exibi-las no álbum.</p></div><button className="secondary-button" disabled={busy} onClick={()=>void load()}>Atualizar</button></div><div className="memory-list">{data.memories.map(m=><article className="memory-row" key={m.id}><div><div className="memory-meta"><strong>{m.author_name}</strong><span className={"status-pill "+m.status}>{m.status==="pending"?"Pendente":m.status==="approved"?"Aprovada":m.status==="rejected"?"Rejeitada":"Oculta"}</span></div><p>{m.message}</p><small>{new Date(m.submitted_at).toLocaleString("pt-BR")}{m.moderation_note?" · "+m.moderation_note:""}</small></div>{m.status!=="approved"&&<div className="memory-actions"><button className="secondary-button" disabled={busy} onClick={()=>void moderate(m.id,"approve")}>Aprovar</button>{m.status!=="rejected"&&<button className="secondary-button" disabled={busy} onClick={()=>void moderate(m.id,"reject")}>Rejeitar</button>}</div>}</article>)}{!data.memories.length&&<div className="empty">Nenhuma mensagem recebida.</div>}</div></section>
 <section className="panel"><div className="panel-heading"><div><h2>Fotos</h2><p>Fotos registradas no sistema e suas decisões de moderação.</p></div></div><div className="memory-list">{data.photos.map(p=><article className="memory-row" key={p.id}><div><div className="memory-meta"><strong>{p.original_filename}</strong><span className={"status-pill "+p.status}>{p.status==="pending"?"Pendente":p.status==="approved"?"Aprovada":p.status==="rejected"?"Rejeitada":"Oculta"}</span></div><small>{new Date(p.uploaded_at).toLocaleString("pt-BR")}</small></div>{p.status!=="approved"&&<div className="memory-actions"><button className="secondary-button" disabled={busy} onClick={()=>void moderate(p.id,"approve",true)}>Aprovar</button><button className="secondary-button" disabled={busy} onClick={()=>void moderate(p.id,"reject",true)}>Rejeitar</button></div>}</article>)}{!data.photos.length&&<div className="empty">Nenhuma foto registrada.</div>}</div></section></div>
}