"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Gift={id:string;title:string;description:string|null;estimated_value:number|null;target_amount:number|null;gift_type:string;status:string;allow_multiple_contributions:boolean;created_at:string};
type Reservation={id:string;gift_id:string;title:string;guest_name:string;guest_email:string|null;status:string;reserved_at:string};
type Contribution={id:string;gift_id:string;title:string;guest_name:string;guest_email:string|null;amount:number;status:string;provider:string|null;provider_reference:string|null;created_at:string;confirmed_at:string|null};
type Data={gifts:Gift[];reservations:Reservation[];contributions:Contribution[];totals:{pending:number;confirmed:number;rejected:number}};
const money=(v:number|null|undefined)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v||0));
export default function GiftManager({eventId}:{eventId:string}){
 const sb=createClient();const [data,setData]=useState<Data>({gifts:[],reservations:[],contributions:[],totals:{pending:0,confirmed:0,rejected:0}});const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
 const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [type,setType]=useState("physical");const [value,setValue]=useState("");const [target,setTarget]=useState("");const [multiple,setMultiple]=useState(true);
 const [reviewId,setReviewId]=useState("");const [provider,setProvider]=useState("manual");const [reference,setReference]=useState("");const [note,setNote]=useState("");
 async function load(){const {data,error}=await sb.rpc("list_event_gifts",{p_event_id:eventId});if(error)throw error;setData((data||{gifts:[],reservations:[],contributions:[],totals:{pending:0,confirmed:0,rejected:0}}) as Data);setLoading(false)}
 useEffect(()=>{void load().catch(e=>{setError(e instanceof Error?e.message:"Falha ao carregar presentes.");setLoading(false)})},[eventId]);
 async function createGift(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setNotice("");try{const {error}=await sb.rpc("manage_gift_item",{p_event_id:eventId,p_gift_id:null,p_title:title,p_description:description,p_value:value?Number(value):null,p_target:target?Number(target):null,p_type:type,p_allow_multiple:multiple});if(error)throw error;setTitle("");setDescription("");setValue("");setTarget("");setNotice("Presente cadastrado.");await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível cadastrar presente.")}finally{setBusy(false)}}
 async function release(id:string){const reason=window.prompt("Motivo para liberar esta reserva:");if(reason===null)return;setBusy(true);setError("");try{const {error}=await sb.rpc("release_gift_reservation",{p_reservation_id:id,p_reason:reason});if(error)throw error;setNotice("Reserva liberada.");await load()}catch(e){setError(e instanceof Error?e.message:"Falha ao liberar reserva.")}finally{setBusy(false)}}
 async function review(action:"confirm"|"reject"){if(!reviewId)return;setBusy(true);setError("");setNotice("");try{const {error}=await sb.rpc("review_gift_contribution",{p_contribution_id:reviewId,p_action:action,p_provider:provider,p_provider_reference:reference,p_note:note});if(error)throw error;setNotice(action==="confirm"?"Confirmação financeira registrada.":"Contribuição rejeitada.");setReviewId("");setReference("");setNote("");await load()}catch(e){setError(e instanceof Error?e.message:"Falha na revisão financeira.")}finally{setBusy(false)}}
 return <div className="gift-manager">{error&&<div className="form-error">{error}</div>}{notice&&<div className="checkin-result accepted">{notice}</div>}
 <div className="gift-totals"><article><span>Confirmado</span><strong>{money(data.totals.confirmed)}</strong></article><article><span>Pendente</span><strong>{money(data.totals.pending)}</strong></article><article><span>Rejeitado</span><strong>{money(data.totals.rejected)}</strong></article></div>
 <section className="panel"><div className="panel-heading"><div><h2>Cadastrar presente</h2><p>Itens físicos ou opções de contribuição financeira.</p></div></div><form className="gift-form" onSubmit={createGift}><label>Nome do presente<input required minLength={2} maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Jogo de taças"/></label><label>Tipo<select value={type} onChange={e=>setType(e.target.value)}><option value="physical">Presente físico</option><option value="cash_contribution">Contribuição financeira</option></select></label><label>Descrição<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={2} maxLength={1000}/></label><label>Valor estimado (R$)<input type="number" min="0" step=".01" value={value} onChange={e=>setValue(e.target.value)} placeholder="Opcional"/></label><label>Meta de contribuição (R$)<input type="number" min=".01" step=".01" value={target} onChange={e=>setTarget(e.target.value)} placeholder="Opcional"/></label>{type==="cash_contribution"&&<label className="gift-checkbox"><input type="checkbox" checked={multiple} onChange={e=>setMultiple(e.target.checked)}/> Permitir contribuições múltiplas</label>}<button className="primary-button" disabled={busy||title.trim().length<2}>Cadastrar presente</button></form></section>
 <section className="panel"><div className="panel-heading"><div><h2>Lista de presentes</h2><p>Reservas são protegidas contra disputa simultânea no banco.</p></div><button className="secondary-button" onClick={()=>void load()} disabled={busy}>Atualizar</button></div>{loading?<p className="muted">Carregando...</p>:<div className="gift-list">{data.gifts.map(g=><article className="gift-row" key={g.id}><div><strong>{g.title}</strong><p>{g.description||"Sem descrição"}</p><small>{g.gift_type==="physical"?"Presente físico":"Contribuição financeira"} · {g.status==="available"?"Disponível":g.status==="reserved"?"Reservado":g.status==="fulfilled"?"Concluído":"Inativo"}</small></div><div className="gift-value">{g.target_amount? "Meta "+money(g.target_amount):money(g.estimated_value)}</div></article>)}{!data.gifts.length&&<div className="empty">Nenhum presente cadastrado ainda.</div>}</div>}</section>
 <section className="panel"><div className="panel-heading"><div><h2>Reservas</h2><p>Histórico de quem reservou cada presente.</p></div></div><div className="gift-list">{data.reservations.map(r=><article className="gift-row" key={r.id}><div><strong>{r.title}</strong><p>{r.guest_name}{r.guest_email?" · "+r.guest_email:""}</p><small>{r.status==="reserved"?"Reserva ativa":r.status==="released"?"Liberada":"Concluída"} · {new Date(r.reserved_at).toLocaleString("pt-BR")}</small></div>{r.status==="reserved"&&<button className="secondary-button" disabled={busy} onClick={()=>void release(r.id)}>Liberar reserva</button>}</article>)}{!data.reservations.length&&<div className="empty">Nenhuma reserva registrada.</div>}</div></section>
 <section className="panel"><div className="panel-heading"><div><h2>Contribuições e Pix</h2><p>Uma intenção pendente não é tratada como pagamento recebido. Confirme apenas após verificar a transação no provedor ou banco.</p></div></div><div className="gift-list">{data.contributions.map(c=><article className="gift-row" key={c.id}><div><strong>{c.title} · {money(c.amount)}</strong><p>{c.guest_name}{c.guest_email?" · "+c.guest_email:""}</p><small>{c.status==="pending"?"Pendente":c.status==="confirmed"?"Confirmado":c.status==="rejected"?"Rejeitado":c.status} · {new Date(c.created_at).toLocaleString("pt-BR")}</small></div><div className="gift-actions">{c.status==="pending"&&<button className="secondary-button" disabled={busy} onClick={()=>{setReviewId(c.id);setReference("");setNote("")}}>Revisar</button>}</div></article>)}{!data.contributions.length&&<div className="empty">Nenhuma contribuição registrada.</div>}</div></section>
 {reviewId&&<div className="modal-backdrop"><section className="panel reversal-modal"><h2>Revisão financeira</h2><p>Registre o provedor e a referência real da transação antes de confirmar. Esta tela não consulta nem movimenta dinheiro.</p><label>Provedor<input value={provider} onChange={e=>setProvider(e.target.value)} placeholder="Ex.: Pix / banco"/></label><label>Referência da transação<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="ID da transação / comprovante"/></label><label>Observação<textarea value={note} onChange={e=>setNote(e.target.value)} rows={3}/></label><div className="invite-actions"><button className="secondary-button" onClick={()=>setReviewId("")}>Cancelar</button><button className="danger-button" disabled={busy} onClick={()=>void review("reject")}>Rejeitar</button><button className="primary-button" disabled={busy||!reference.trim()} onClick={()=>void review("confirm")}>Confirmar pagamento</button></div></section></div>}
 </div>
}
