"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";
type Row={invitation_id:string;guest_id:string;family_id:string;guest_name:string;family_name:string;status:string;issued_at:string;expires_at:string|null;latest_stage:number;final_attendance:string|null};
export default function InvitationManager({eventId}:{eventId:string}){
 const sb=createClient();const [rows,setRows]=useState<Row[]>([]),[settings,setSettings]=useState<any>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 async function load(){const [a,b]=await Promise.all([sb.rpc("list_event_invitations",{p_event_id:eventId}),sb.rpc("ensure_invitation_settings",{p_event_id:eventId})]);if(a.error)throw a.error;if(b.error)throw b.error;setRows(a.data||[]);setSettings(b.data)}
 useEffect(()=>{void load().catch(e=>setErr(e instanceof Error?e.message:"Não foi possível carregar os convites."))},[eventId]);
 async function issue(guestId:string){setBusy(true);setErr("");setMsg("");try{const {data,error}=await sb.rpc("issue_invitation",{p_guest_id:guestId});if(error)throw error;const url=window.location.origin+"/convite/"+data.token;await navigator.clipboard?.writeText(url);setMsg("Convite gerado. O link foi copiado quando permitido pelo navegador.");await load()}catch(e){setErr(e instanceof Error?e.message:"Falha ao gerar convite.")}finally{setBusy(false)}}
 async function revoke(id:string){setBusy(true);try{const {error}=await sb.rpc("revoke_invitation",{p_invitation_id:id});if(error)throw error;setMsg("Convite revogado.");await load()}catch(e){setErr(e instanceof Error?e.message:"Falha ao revogar.")}finally{setBusy(false)}}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setErr("");try{const f=new FormData(e.currentTarget);const v=(n:string)=>f.get(n)==="on";const {data,error}=await sb.rpc("update_invitation_settings",{p_event_id:eventId,p_stage1_open:v("s1"),p_stage1_deadline:null,p_stage2_open:v("s2"),p_stage2_deadline:null,p_stage3_open:v("s3"),p_stage3_deadline:null});if(error)throw error;setSettings(data);setMsg("Etapas atualizadas.")}catch(e){setErr(e instanceof Error?e.message:"Falha ao atualizar etapas.")}finally{setBusy(false)}}
 return <div className="invite-admin"><div className="panel"><div className="panel-heading"><div><h2>Liberação das etapas</h2><p>A URL nunca antecipa uma etapa fechada.</p></div></div>{settings&&<form className="stage-settings" onSubmit={save}><label className="check-row"><input name="s1" type="checkbox" defaultChecked={settings.stage1_open}/> Etapa 1 — primeira resposta</label><label className="check-row"><input name="s2" type="checkbox" defaultChecked={settings.stage2_open}/> Etapa 2 — informações adicionais</label><label className="check-row"><input name="s3" type="checkbox" defaultChecked={settings.stage3_open}/> Etapa 3 — confirmação final + ingresso</label><button className="primary-button" disabled={busy}>Salvar liberação</button></form>}</div>{msg&&<div className="notice success">{msg}</div>}{err&&<div className="form-error">{err}</div>}<div className="panel"><div className="panel-heading"><div><h2>Convites individuais</h2><p>Links aleatórios, revogáveis e reemitíveis.</p></div></div><div className="invite-list">{rows.map(r=><div className="invite-row" key={r.invitation_id}><div><strong>{r.guest_name}</strong><span>{r.family_name} · etapa {r.latest_stage}/3 · {r.final_attendance==="yes"?"confirmado":r.status}</span></div><div className="invite-actions">{r.status==="active"&&<><button className="text-button-static" disabled={busy} onClick={()=>void issue(r.guest_id)}>Reemitir</button><button className="text-button-static danger-text" disabled={busy} onClick={()=>void revoke(r.invitation_id)}>Revogar</button>{r.final_attendance==="yes"&&<Link className="text-button-static" href={"/convite/"+""} aria-disabled>Ingresso</Link>}</>}</div></div>)}{!rows.length&&<div className="empty">Nenhum convite emitido.</div>}</div></div></div>
}
